define(function(){
    return [
        {
            title:'成都',
            path:'/org'
        },
        {
            title:'绵阳',
            path:'/org'
        },
        {
            title:'攀枝花',
            path:'/org'
        },
        {
            title:'达州',
            path:'/org'
        },
        {
            title:'宜宾',
            path:'/org'
        },
        {
            title:'凉山',
            path:'/org'
        },
        {
            title:'潍坊',
            path:'/org'
        },
        {
            title:'淄博',
            path:'/org'
        },
        {
            title:'济南',
            path:'/org'
        },
        {
            title:'济宁',
            path:'/org'
        },
        {
            title:'枣庄',
            path:'/org'
        },
        {
            title:'德州',
            path:'/org'
        },
        {
            title:'菏泽',
            path:'/org'
        },
        {
            title:'东营',
            path:'/org'
        },
        {
            title:'泰安',
            path:'/org'
        },
        {
            title:'青岛',
            path:'/org'
        },
        {
            title:'廊坊',
            path:'/org'
        },
        {
            title:'唐山',
            path:'/org'
        },
        {
            title:'秦皇岛',
            path:'/org'
        },
        {
            title:'石家庄',
            path:'/org'
        },
        {
            title:'福州',
            path:'/org'
        },
        {
            title:'厦门',
            path:'/org'
        },
        {
            title:'泉州',
            path:'/org'
        },
        {
            title:'漳州',
            path:'/org'
        },
        {
            title:'南京',
            path:'/org'
        },
        {
            title:'常州',
            path:'/org'
        },
        {
            title:'连云港',
            path:'/org'
        },
        {
            title:'南通',
            path:'/org'
        },
        {
            title:'广州',
            path:'/org'
        },
        {
            title:'深圳',
            path:'/org'
        },
        {
            title:'珠海',
            path:'/org'
        },
        {
            title:'佛山',
            path:'/org'
        },
        {
            title:'肇庆',
            path:'/org'
        },
        {
            title:'阳江',
            path:'/org'
        },
        {
            title:'东莞',
            path:'/org'
        },
        {
            title:'惠州',
            path:'/org'
        },
        {
            title:'昆明',
            path:'/org'
        },
        {
            title:'曲靖',
            path:'/org'
        },
        {
            title:'六盘水',
            path:'/org'
        },
        {
            title:'毕节',
            path:'/org'
        },
        {
            title:'重庆',
            path:'/org'
        },
        {
            title:'衡阳',
            path:'/org'
        },
        {
            title:'郑州',
            path:'/org'
        },
        {
            title:'洛阳',
            path:'/org'
        },
        {
            title:'南阳',
            path:'/org'
        },
        {
            title:'西安',
            path:'/org'
        },
        {
            title:'赣州',
            path:'/org'
        },
        {
            title:'嘉兴',
            path:'/org'
        },
        {
            title:'沈阳',
            path:'/org'
        },
        {
            title:'鞍山',
            path:'/org'
        },
        {
            title:'南宁',
            path:'/org'
        },
        {
            title:'长沙',
            path:'/org'
        },
        {
            title:'上海',
            path:'/org'
        }
    ]
});
