define(function(){
    return {
        sponsorUnit: [
            {
                name: '中国关心下一代工作委员会'
            },
            {
                name: '中华人民共和国教育部'
            },
            {
                name: '中华人民共和国司法部'
            },
            {
                name: '中华人民共和国农业部'
            },
            {
                name: '中华人民共和国文化部'
            },
            {
                name: '中华人民共和国卫生部'
            },
            {
                name: '国家质量监督检验检疫总局'
            },
            {
                name: '国家广播电视总局'
            },
            {
                name: '国家体育总局'
            },
            {
                name: '国家安全生产监督管理总局'
            },
            {
                name: '国家食品药品监督管理局'
            },
            {
                name: '国务院法制办公室'
            }
        ],
        organizer: [
            {
                name: '中国关心下一代工作委员会健康体育发展中心'
            },
            {
                name: '中国青少年艺术素质教育系列活动办公室'
            }
        ],
        /*hostingArea: [
            {
                province:'四川省',
                children:[
                    {
                        area:'成都地区'
                    },
                    {
                        area:'绵阳地区'
                    },
                    {
                        area:'攀枝花地区'
                    },
                    {
                        area:'达州地区'
                    },
                    {
                        area:'宜宾地区'
                    },
                    {
                        area:'凉山地区'
                    }
                ]
            },
            {
                province:'山东省',
                children:[
                    {
                        area:'潍坊地区'
                    },
                    {
                        area:'淄博地区'
                    },
                    {
                        area:'济南地区'
                    },
                    {
                        area:'济宁地区'
                    },
                    {
                        area:'枣庄地区'
                    },
                    {
                        area:'德州地区'
                    },
                    {
                        area:'菏泽地区'
                    },
                    {
                        area:'东营地区'
                    },
                    {
                        area:'泰安地区'
                    },
                    {
                        area:'青岛地区'
                    }
                ]
            },
            {
                province:'河北省',
                children:[
                    {
                        area:'廊坊地区'
                    },
                    {
                        area:'唐山地区'
                    },
                    {
                        area:'秦皇岛地区'
                    },
                    {
                        area:'石家庄地区'
                    }
                ]
            },
            {
                province:'福建省',
                children:[
                    {
                        area:'福州地区'
                    },
                    {
                        area:'厦门地区'
                    },
                    {
                        area:'泉州地区'
                    },
                    {
                        area:'漳州地区'
                    }
                ]
            },
            {
                province:'江苏省',
                children:[
                    {
                        area:'南京地区'
                    },
                    {
                        area:'常州地区'
                    },
                    {
                        area:'连云港地区'
                    },
                    {
                        area:'南通地区'
                    }
                ]
            },
            {
                province:'广东省',
                children:[
                    {
                        area:'广州地区'
                    },
                    {
                        area:'深圳地区'
                    },
                    {
                        area:'深圳地区'
                    },
                    {
                        area:'佛山地区'
                    },
                    {
                        area:'肇庆地区'
                    },
                    {
                        area:'肇庆地区'
                    },
                    {
                        area:'东莞地区'
                    },
                    {
                        area:'惠州地区'
                    }
                ]
            },
            {
                province:'云南省',
                children:[
                    {
                        area:'昆明地区'
                    },
                    {
                        area:'曲靖地区'
                    }
                ]
            },
            {
                province:'贵州省',
                children:[
                    {
                        area:'六盘水地区'
                    },
                    {
                        area:'毕节地区'
                    },
                    {
                        area:'秦皇岛地区'
                    },
                    {
                        area:'石家庄地区'
                    }
                ]
            },
            {
                province:'河南省',
                children:[
                    {
                        area:'郑州地区'
                    },
                    {
                        area:'洛阳地区'
                    },
                    {
                        area:'南阳地区'
                    }
                ]
            },
            {
                province:'辽宁省',
                children:[
                    {
                        area:'沈阳地区'
                    },
                    {
                        area:'鞍山地区'
                    }
                ]
            },
            {
                province:'重庆市',
                children:[
                    {
                        area:'重庆地区'
                    }
                ]
            },
            {
                province:'上海市',
                children:[
                    {
                        area:'上海地区'
                    }
                ]
            },
            {
                province:'湖南省',
                children:[
                    {
                        area:'长沙地区'
                    },
                    {
                        area:'衡阳地区'
                    }
                ]
            },
            {
                province:'陕西省',
                children:[
                    {
                        area:'西安地区'
                    }
                ]
            },
            {
                province:'江西省',
                children:[
                    {
                        area:'赣州地区'
                    }
                ]
            },
            {
                province:'浙江省',
                children:[
                    {
                        area:'嘉兴地区'
                    }
                ]
            },
            {
                province:'广西省',
                children:[
                    {
                        area:'南宁地区'
                    }
                ]
            }
        ]*/

        hostingArea: [
            {
                province:'四川',
                children:[
                    {
                        area:'成都地区'
                    },
                    {
                        area:'绵阳地区'
                    },
                    {
                        area:'攀枝花地区'
                    },
                    {
                        area:'达州地区'
                    },
                    {
                        area:'宜宾地区'
                    },
                    {
                        area:'梁山地区'
                    }
                ]
            },
            {
                province:'山东',
                children:[
                    {
                        area:'潍坊地区'
                    },
                    {
                        area:'淄博地区'
                    },
                    {
                        area:'济南地区'
                    },
                    {
                        area:'东营地区'
                    },
                    {
                        area:'泰安地区'
                    },
                    {
                        area:'青岛地区'
                    }
                ]
            },
            {
                province:'河北',
                children:[
                    {
                        area:'廊坊地区'
                    },
                    {
                        area:'唐山地区'
                    },
                    {
                        area:'秦皇岛地区'
                    },
                    {
                        area:'石家庄地区'
                    }
                ]
            }
        ]
    }
});